site_name: AdventuresCraft Wiki
site_url: https://www.adventurescraft.net/wiki/site/index.html
site_description: Wikipedia for the Minecraft MMORPG Server, AdventuresCraft!
site_author: Monzter
copyright: "© AdventuresCraft 2021"

repo_name: AdventuresQuest
edit_uri: /Dancull47/AdventuresQuest/edit/master/wiki/docs
repo_url: https://github.com/Dancull47/AdventuresQuest


theme:
  name: material
  language: en
  features:
    - navigation.instant
    - search.highlight
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: img/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bw4DztR
    - icon: fontawesome/solid/home
      link: https://www.adventurescraft.net/
    - icon: fontawesome/solid/credit-card
      link: http://store.adventurescraft.net/

nav:
  - 'Home': 
      - 'Overview': index.md
      - 'Vote': vote.md
      - 'Commands': commands.md
      - 'Resource Pack': resource-pack.md
      - 'Dev Log': dev-log.md
      #- 'FAQ': faq.md
  - 'Professions':
      - 'Overview': professions/overview.md
      - 'Farming': professions/farming.md
  - 'Areas':
      - 'Overview': areas/overview.md
      - 'Farming': areas/farm.md
      - 'Cavern': areas/cavern.md
      - 'Void': areas/void.md
  - 'Defense':
      - 'Castle': defense/castle.md
      #- 'Getting Started':
       #   - Learn-Beton/Getting-Started/Setting-up-a-local-test-server.md
        #  - Learn-Beton/Getting-Started/Installing-BetonQuest.md
         # - Learn-Beton/Getting-Started/Setting-up-the-editor.md
          #- Learn-Beton/Getting-Started/Quick-Start-Tutorial.md
      #- Learn-Beton/Frequently-Asked-Questions.md
      #- Learn-Beton/Tips-and-tricks.md
